### ISSUE TITLE
rows.Err() is no joke

### ISSUE THREAD

**Issue by johto** [mmcgrana/pgpin#2]
Hi,

(Just passing by as I saw this project referenced somewhere).

Iterating over the result set like [this](https://github.com/mmcgrana/pgpin/blob/89402d4786697dbbdf31ceb66ccb199c631b637b/model.go#L225) is not enough.  After rows.Next() has returned false, you have to also check rows.Err().  See e.g. http://go-database-sql.org/retrieving.html.

**Comment by mmcgrana** [comment]
Good catch @johto, thanks for the tip. I'll look into a patch
for this.
